### ISSUE TITLE
Resolving timed out

### ISSUE THREAD

**Issue by hlherrera** [paypal/rest-api-sample-app-php#14] opened 2015-01-08 20:41 UTC
I was running the app through a proxy:
I had configured the http.Proxy variable in 'sdk_config.ini' file.

When I ran the app I had this error:
-- Resolving timed out after 10516 milliseconds --

**Comment by jaypatel512** [comment] 2015-01-08 20:42
Let me reproduce this in my local machine, and get back to you.

**Comment by jaypatel512** [comment] 2015-01-27 17:22
Hey @hlherrera !! 

I am not able to reproduce this issue. Whenever I try to connect via a proxy, it connects succesfully in my machine. There are several factors that may be affecting the connection. Can you please make sure you have your firewall settings not blocking them.

You could use a network traffic inspector to see where the connection is getting blocked. I am closing this issue right now, but if you are still facing the trouble, please feel free to re-open this again. 

Thanks @hlherrera

**Closed by jaypatel512** 2015-01-27 17:22 UTC
Labels: question
