### ISSUE TITLE
setExpireMonth() -> undefinfed method

### ISSUE THREAD

**Issue by harshalpatel** [paypal/rest-api-sample-app-php#19] opened 2015-06-18 22:22 UTC
When creating an account, receive this error:

Fatal error: Call to undefined method PayPal\Api\CreditCard::setExpireMonth() in /home/admin/public_html/rest-api-sample-app-php-master/app/common/paypal.php

**Comment by jaypatel512** [comment] 2015-06-18 23:39
I am not able to reproduce the issue. Can you please make sure you have vendor directory ? And if so, can you look for `setExpireMonth` method in vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/CreditCard.php.

Also, in the vendor/paypal/rest-api-sdk-php/release_notes.md, you should see that the latest version of 1.4.0 is present. 

Let me know if that helps.

**Comment by jaypatel512** [comment] 2015-06-18 23:39
Closed by mistake.

**Comment by harshalpatel** [comment] 2015-06-18 23:49
In the library the function has an underscore: 
    	public function setExpire_month($expire_month) {
		$this->expire_month = $expire_month;
	}

Seems to be old version:
REST API SDK for PHP  (V0.5.0)

I had 1.2 in composer; should it be 1.5?
{
    "require": {
        "aws/aws-sdk-php": "2.*",
        "mandrill/mandrill": "1.0.*",
        "paypal/rest-api-sdk-php" : "0.5.*",
        "php": ">=5.3.0",
        "ext-curl": "*",
        "ext-json": "*",
        "paypal/sdk-core-php": "1.2.*"
    }
}

**Comment by jaypatel512** [comment] 2015-06-19 00:12
You are using a lot older sdk. Please update your composer.json to have something like this:

```
{
    "require": {
        "aws/aws-sdk-php": "2.*",
        "mandrill/mandrill": "1.0.*",
        "paypal/rest-api-sdk-php" : "1.*",
        "php": ">=5.3.0",
        "ext-curl": "*",
        "ext-json": "*"
    }
}
```

Remove `sdk-core-php` and update `rest-api-sdk-php` to use 1.*.

Re-open the issue if the problem still exists.

**Closed by jaypatel512** 2015-06-19 00:12 UTC
